# Preliminary Content {-}

## Acknowledgements {-}

I would like to thank my supervisors, Steve Fleming, for being a wonderful scientific mentor and role-model, and Karl Friston, for your generous advice and support. Steve, I am ever grateful for these four years of training in the supportive, excellence-seeking environment that you cultivated in the UCL MetaLab. I had the privilege of collaborating with amazing scientists, including Lucie Charles, Rani Moran, Roy Tal, Chudi Gong and Nadine Dijkstra. For their help and support, I thank Peter Zeidman, Dan Bang, Max Rollwage, Marion Rouault, and the FIL imaging support team, as well as a supportive international network of scientists, including Felix Henninger, Elisa Filevich, Kristian Lange, Chester Ismay, Brian Maniscalco, Arial Zylberberg, Jorge Morales, my wonderful examiners David Lagnado and Heleen Slagter, and the twitter and Stack Exchange communities. I thank Josh Tenenbaum and Tomer Ullman for your mentorship in my visit to MIT and Harvard, and the Bogue Fellowship committee for their decision to support this career-changing visit. This PhD would not have been possible without UCL's Graduate and Overseas Research Scholarships, and it would have been much harder without the support of a Kenneth Lindsay Scholarship. I am grateful to my mentors from Tel Aviv University: Roy Mukamel, Liad Mudrik, Naama Friedman and Roni Katzir, for believing in me as a junior cognitive scientist and patiently guiding me in my first steps. My friends at the Wellcome Centre for Human Neuroimaging and MetaLab  - you made these years not only enriching and educating, but also memorable and enjoyable. Dina Silanteva, Alisa Loosen and the Hackney Wick gang - thanks for being the best support bubble in times of a global pandemic. I thank the Mary Ward Cafe at Queen Square and the Hari Krishna volunteers for the vegan food that kept my brain going. My friends Darya Mosenzon, Halely Balaban, Maya Ankaoua, Maayan Keshev, Roni Maimon, Netta Green, Alon Rubin, Ezer Rasin and Yohai Szulszepper - thanks for being there for me.  Amnon David Ar - you taught me how to be a painter. I'll forever be indebted for your lessons about observation, friendship and perseverance, which are still shaping the person and researcher I am striving to be today. My parents Ora and Shai, you care about this arbitrary academic title much less than you want me to be happy and stand up for my principles. תודה. Finally, I would like to thank my brother Noam, and our four-legged, hairy and smelly friend, B7, for being my companions and compass in this long journey.


## Impact Statement {-}

This thesis is submitted in the strange world of 2021. Twice a week, I start my day with a rapid lateral flow covid-19 test. I wipe a swab inside my nostrils, transfer the sample into a liquid and then place two drops on a test kit. I then wait to read the results: two lines indicate a positive result, and one line a negative one. But why does the test need to have two lines? Why can’t a line indicate a positive result, and zero lines a negative one?

  For a positive test result, this additional control line doesn’t add much. Its importance is for interpreting a negative test. Two lines indicate that covid-19 antigens were detected, one line indicates that covid-19 antigens were not detected and that the test is working, and zero lines indicate that antigens were not detected, but that this is not very informative, because other things that should have been detected were not detected either. Without this additional control line, we have no way of telling between these last two options.

Detecting the presence of covid-19 antigens in a sample is conceptually similar to other detection and search tasks, such as detecting the presence or absence of a red sock in a drawer. But unlike the covid test, upon not finding a red sock I don’t have a control line to indicate that the sock would have been found if it were present, or that my vision is intact. Instead, I need to rely on some knowledge about my perception and attention - for example that I would not have missed the sock if it were there. This is a unique feature of decisions about the *absence* of things: without a positive control, they must rely on some form of *self-modelling*.

In a series of studies I examine behavioural and neural activation patterns in visual detection and visual search tasks, and ask whether they provide evidence for reliance on self-modelling, specifically when participants report the absence of stimuli. In carrying out this research I adopted high standards of transparency and openness: all experiments were pre-registered and time-locked with respect to data acquisition, all data (including raw neuroimaging data) is openly shared, and my analysis scripts are openly available. The thesis itself is written using the R package thesisdown, making all statistical analysis 100% reproducible. Some findings from these studies are published in eLife, and as a Registered Report in Neuroscience of Consciousness, and other parts are currently being reviewed for publication.

This thesis opens a novel research programme, using inference about absence to ask questions about self-modelling. In these first studies I focused on healthy adults, but in the future these ideas hold promise for understanding psychological conditions such as obsessive compulsive disorder, where the bar for inferring absence (for example, of germs on one’s hand) is set exceptionally high. I hope my PhD output inspires further research on inference about absence, and its reliance on self-modelling.

## Dedication {-}

  To my fellow non-human primates of Queen Square, whose experience of London was very different to mine.

<!-- `r if(!knitr:::is_latex_output()) '## Abstract {-}'` -->
